name: Generate Contribution Garden

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  build_garden:
    runs-on: ubuntu-latest
    permissions: 
      contents: write # Important: Allow workflow to write to repository

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r garden_generator/requirements.txt
      
      - name: Generate Contribution Garden SVG
        env:
          GH_TOKEN_GARDEN: ${{ secrets.GH_TOKEN_GARDEN }} # Use the GitHub secret
        run: python garden_generator/main.py

      - name: Commit and push if changes
        run: |
          git config --global user.name "Contribution Garden Bot"
          git config --global user.email "actions@github.com" # Or your email
          git add output/contribution_garden.svg
          # Commit only if there are changes
          git diff --staged --quiet || git commit -m "feat: auto-update contribution garden 🌳"
          git push
