      name: Update README with Recent Activity
      on:
         schedule:
           - cron: '0 */4 * * *'
         workflow_dispatch:
      jobs:
         build:
           runs-on: ubuntu-latest
           name: Update Profile README
           steps:
             - uses: actions/checkout@v3
             - uses: jamesgeorge007/github-activity-readme@master
               env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
               with:
                 MAX_LINES: 10
                 COMMIT_MSG: 'docs: update recent GitHub activity feed'
